import MathPaper

#print axioms MathPaper.modulus_factorization
#print axioms MathPaper.base_is_reduced
#print axioms MathPaper.subdivision_endpoint
#print axioms MathPaper.fractionOrbit_nonneg
#print axioms MathPaper.fractionOrbit_lt_one
#print axioms MathPaper.carry_fraction
#print axioms MathPaper.carry_bounds
#print axioms MathPaper.floor_orbit_eventually_gt
#print axioms MathPaper.homogeneous_integer_sequence_zero
#print axioms MathPaper.carry_not_eventually_periodic
#print axioms MathPaper.floor_carry_not_eventually_periodic
#print axioms MathPaper.orbit_edge
#print axioms MathPaper.floor_refinement_bounds
#print axioms MathPaper.refined_state_mem
#print axioms MathPaper.rank_eventually_constant
#print axioms MathPaper.phase_labels_periodic
#print axioms MathPaper.rank_certificate_retained_tail
#print axioms MathPaper.gcd_emod
#print axioms MathPaper.orbit_state_legal
#print axioms MathPaper.certified_orbit_retained_tail
#print axioms MathPaper.finite_success_visits
#print axioms MathPaper.composite_of_gcd_gt_one
#print axioms MathPaper.finite_success_composite
#print axioms MathPaper.edge_interval_iff
#print axioms MathPaper.main_congruence_candidate
#print axioms MathPaper.main_cell_candidate
#print axioms MathPaper.main_carry_candidate
#print axioms MathPaper.mainFiniteSuccess
#print axioms MathPaper.floor_seven_fifths_visits
#print axioms MathPaper.floor_seven_fifths_composite

-- Word-labelled method: the theory uses standard axioms; concrete pipelines add native_decide-generated evaluation axioms.
#print axioms MathPaper.Covering.output_concatFrom
#print axioms MathPaper.Covers.map
#print axioms MathPaper.phase_output_periodic
#print axioms MathPaper.chain_realized
#print axioms MathPaper.macro_visited
#print axioms MathPaper.contract_tail
#print axioms MathPaper.WordCert.owner_eventually_constant
#print axioms MathPaper.WordCert.stage_tail
#print axioms MathPaper.step_orbit
#print axioms MathPaper.runWord_orbit
#print axioms MathPaper.lift_tail
#print axioms MathPaper.wordChain_no_covering
#print axioms MathPaper.initial_covering
#print axioms MathPaper.word_finite_success_visits
#print axioms MathPaper.word_finite_success_composite
#print axioms MathPaper.carry_alphabet_52
#print axioms MathPaper.carry_alphabet_75
#print axioms MathPaper.Pipe.allIdx_spec
#print axioms MathPaper.Pipe.phaseCheck_sound
#print axioms MathPaper.Pipe.contractCheck_sound
#print axioms MathPaper.Pipe.edgeCheck_sound
#print axioms MathPaper.Pipe.checkStage_sound
#print axioms MathPaper.Pipe.liftArr_sound
#print axioms MathPaper.Pipe.initialStage_sound
#print axioms MathPaper.Pipe.go_sound
#print axioms MathPaper.Pipe.wordPipeline_sound
#print axioms MathPaper.five_halves_ok
#print axioms MathPaper.five_halves_success
#print axioms MathPaper.floor_five_halves_visits
#print axioms MathPaper.floor_five_halves_composite
#print axioms MathPaper.seven_fifths_ok
#print axioms MathPaper.seven_fifths_success_word
#print axioms MathPaper.floor_seven_fifths_visits_word
