name = "math-paper"
version = "0.1.0"
defaultTargets = ["MathPaper"]

[leanOptions]
warningAsError = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5e932f97dd25535344f80f9dd8da3aab83df0fe6"

[[lean_lib]]
name = "MathPaper"
globs = ["MathPaper", "MathPaper.+"]
